ae_user:
    resource: "@AEUserBundle/Controller/"
    type:     annotation
    prefix:   /user

ae_platform:
    resource: "@AEPlatformBundle/Controller/"
    type:     annotation
    prefix:   /platform
