<?php

namespace AE\PlatformBundle\Repository;

/**
 * FiliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliationRepository extends \Doctrine\ORM\EntityRepository
{
}
