<?php

namespace AE\PlatformBundle\Repository;

/**
 * PCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PCRepository extends \Doctrine\ORM\EntityRepository
{
}
